apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ .Release.Name }}-server
      containers:
        - name: server
          image: ghcr.io/lukaspj/talos-cluster-operator/talos-cluster-operator:{{ .Values.image.tag }}
          command:
            - /talos-cluster-operator
            - server
            - --machine-cidr={{ .Values.machines.cidr }}
          ports:
            - containerPort: 4242
              name: http
              protocol: TCP
          startupProbe:
            httpGet:
              port: 4242
              path: /readyz
          livenessProbe:
            httpGet:
              port: 4242
              path: /livez
          readinessProbe:
            httpGet:
              port: 4242
              path: /readyz
          volumeMounts:
            - mountPath: /var/run/secrets/talos.dev
              name: talos-secrets
      volumes:
        - name: talos-secrets
          secret:
            secretName: {{ .Release.Name }}-server
